version: 0.0
os: linux

files:
  - source: app-tier/
    destination: /home/ec2-user/app-tier

permissions:
  - object: /home/ec2-user/app-tier
    pattern: "**"
    owner: ec2-user
    group: ec2-user