version: 0.0
os: linux
files:
  - source: app-tier/
    destination: /home/ec2-user/app-tier

hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      runas: ec2-user
