version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Moving into app directory
      - cd app-tier
      - npm install

artifacts:
  files:
    - app-tier/**/*  # Package everything inside app-tier folder
    - appspec.yml    # Also include appspec.yml because CodeDeploy needs it
    - scripts/***    # If you have scripts (install_dependencies.sh, start_app.sh)
  discard-paths: no
